import { POSSIBLE_DIRECTIONS } from "./possible-direction"

export const ANY_DIRECTIONS = [
  POSSIBLE_DIRECTIONS.right,
  POSSIBLE_DIRECTIONS.up,
  POSSIBLE_DIRECTIONS.down,
  POSSIBLE_DIRECTIONS.upRight,
  POSSIBLE_DIRECTIONS.downRight,
  POSSIBLE_DIRECTIONS.left,
  POSSIBLE_DIRECTIONS.upLeft,
  POSSIBLE_DIRECTIONS.downLeft,
]
