import { POSSIBLE_DIRECTIONS } from "./possible-direction.js"

export const FORWARD_DIRECTIONS = [
  POSSIBLE_DIRECTIONS.right,
  POSSIBLE_DIRECTIONS.up,
  POSSIBLE_DIRECTIONS.down,
  POSSIBLE_DIRECTIONS.upRight,
  POSSIBLE_DIRECTIONS.downRight,
]
